## SPDX-License-Identifier: GPL-2.0-only

bootblock-y += bootblock.c ec.c

romstage-y += variants/$(VARIANT_DIR)/memory_init_params.c

ramstage-y += ramstage.c ec.c
ramstage-y += variants/$(VARIANT_DIR)/gpio.c variants/$(VARIANT_DIR)/hda_verb.c
ramstage-$(CONFIG_MAINBOARD_USE_LIBGFXINIT) += variants/$(VARIANT_DIR)/gma-mainboard.ads

cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_0.bin
spd_0.bin-file := variants/$(VARIANT_DIR)/spd/spd_0.bin
spd_0.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_1.bin
spd_1.bin-file := variants/$(VARIANT_DIR)/spd/spd_1.bin
spd_1.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_2.bin
spd_2.bin-file := variants/$(VARIANT_DIR)/spd/spd_2.bin
spd_2.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_3.bin
spd_3.bin-file := variants/$(VARIANT_DIR)/spd/spd_3.bin
spd_3.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_4.bin
spd_4.bin-file := variants/$(VARIANT_DIR)/spd/spd_4.bin
spd_4.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_5.bin
spd_5.bin-file := variants/$(VARIANT_DIR)/spd/spd_5.bin
spd_5.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_6.bin
spd_6.bin-file := variants/$(VARIANT_DIR)/spd/spd_6.bin
spd_6.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_7.bin
spd_7.bin-file := variants/$(VARIANT_DIR)/spd/spd_7.bin
spd_7.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_8.bin
spd_8.bin-file := variants/$(VARIANT_DIR)/spd/spd_8.bin
spd_8.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_9.bin
spd_9.bin-file := variants/$(VARIANT_DIR)/spd/spd_9.bin
spd_9.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_10.bin
spd_10.bin-file := variants/$(VARIANT_DIR)/spd/spd_10.bin
spd_10.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_11.bin
spd_11.bin-file := variants/$(VARIANT_DIR)/spd/spd_11.bin
spd_11.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_12.bin
spd_12.bin-file := variants/$(VARIANT_DIR)/spd/spd_12.bin
spd_12.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_13.bin
spd_13.bin-file := variants/$(VARIANT_DIR)/spd/spd_13.bin
spd_13.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_14.bin
spd_14.bin-file := variants/$(VARIANT_DIR)/spd/spd_14.bin
spd_14.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_15.bin
spd_15.bin-file := variants/$(VARIANT_DIR)/spd/spd_15.bin
spd_15.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_16.bin
spd_16.bin-file := variants/$(VARIANT_DIR)/spd/spd_16.bin
spd_16.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_17.bin
spd_17.bin-file := variants/$(VARIANT_DIR)/spd/spd_17.bin
spd_17.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_18.bin
spd_18.bin-file := variants/$(VARIANT_DIR)/spd/spd_18.bin
spd_18.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_19.bin
spd_19.bin-file := variants/$(VARIANT_DIR)/spd/spd_19.bin
spd_19.bin-type := raw
cbfs-files-$(CONFIG_BOARD_LENOVO_T480S) += spd_20.bin
spd_20.bin-file := variants/$(VARIANT_DIR)/spd/spd_20.bin
spd_20.bin-type := raw
